NUMPY ASSIGNMENTS

1.	Create a 1D array of numbers from 0 to 9.

In [1]:
import numpy as np

x = np.arange(0,10)
print("**** Create a 1D array of numbers from 0 to 9****")
print("\n 1-D array from 0 to 9 :",x)


**** Create a 1D array of numbers from 0 to 9****

 1-D array from 0 to 9 : [0 1 2 3 4 5 6 7 8 9]


2.	Create a 3×3 numpy array of all True’s

In [2]:
import numpy as np
x = np.ones(shape=(3,3),dtype=bool)
print("****Create a 3×3 numpy array of all True’s****")
print("\n 3×3 numpy array of all True’s :",x)


****Create a 3×3 numpy array of all True’s****

 3×3 numpy array of all True’s : [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


3.	Given an array as input, print only odd numbers as output

In [3]:
import numpy as np
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("****Given an array as input, print only odd numbers as output****")
print("Input array :", x)
n = x.shape
i = 0
j = 0
for i in range(0,n[0]):
    for j in range(0,n[1]):
        if ((x[i][j])%2 != 0):
            print(x[i][j])

****Given an array as input, print only odd numbers as output****
Input array : [[1 2 3]
 [4 5 6]
 [7 8 9]]
1
3
5
7
9


In [5]:
#4.	Replace all odd numbers in arr with -2
import numpy as np

x = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("****Replace all odd numbers in arr with -2****")
print("Input array :", x)
n = x.shape
i = 0
j = 0
for i in range(0,n[0]):
    for j in range(0,n[1]):
        if ((x[i][j])%2 != 0):
	        x[i][j] = -2

print("Output array :",x)


****Replace all odd numbers in arr with -2****
Input array : [[1 2 3]
 [4 5 6]
 [7 8 9]]
Output array : [[-2  2 -2]
 [ 4 -2  6]
 [-2  8 -2]]


In [6]:
# 5.	How to reshape an array?
import numpy as np
x = np.array([[1,2,3],[4,5,6]])
print("****5. How to reshape an array?****")
print("Input array :", x)
print("Output array :",x.reshape(3,2))


****5. How to reshape an array?****
Input array : [[1 2 3]
 [4 5 6]]
Output array : [[1 2]
 [3 4]
 [5 6]]


In [7]:
#6.	Convert a 1D array to a 2D array with 2 rows
import numpy as np
x = np.arange(0,8)
print("****6. Convert a 1D array to a 2D array with 2 rows****")
print("Input array :", x)
print("Output array :",x.reshape(2,4))


****6. Convert a 1D array to a 2D array with 2 rows****
Input array : [0 1 2 3 4 5 6 7]
Output array : [[0 1 2 3]
 [4 5 6 7]]


In [9]:
#7.	Given an array  a  = [1,2,3,4,5,6,7,8,9] , create  new array b from a such that b includes all odd numbers and 4 multiples. 
import numpy as np

a = np.arange(1,10)
print("****Given an array  a  = [1,2,3,4,5,6,7,8,9] , create  new array b from a such that b includes all odd numbers and 4 multiples.****")
print("Input array a :", a)
n = len(a)
count = 0
for i in range(0,n):
    if ((a[i]%2 != 0) or (a[i]%4 == 0)):
        count += 1
b = np.empty(count,dtype=int)
j = 0
for i in range(0,n):
    if ((a[i]%2 != 0) or (a[i]%4 == 0)):
        b[j] = a[i]
        j +=1
print("New array b :",b)


****Given an array  a  = [1,2,3,4,5,6,7,8,9] , create  new array b from a such that b includes all odd numbers and 4 multiples.****
Input array a : [1 2 3 4 5 6 7 8 9]
New array b : [1 3 4 5 7 8 9]


In [11]:
# 8.	Given array, check if there are any null values and print them out. 
import numpy as np
a = np.array([[1,2, np.nan ],[4, np.nan ,6],[np.nan ,8, 9]])
print("****Given array, check if there are any null values and print them out.****")
print("Input array a :", a)
n = a.shape
i = 0
j = 0
result = np.equal(np.isnan(a),True)
print("\n Output :")
for i in range(0,n[0]):
    for j in range(0,n[1]):
        if result[i][j] == True:
            print("Element in Row {} and Column {} is {}".format(i,j,a[i][j]))


****Given array, check if there are any null values and print them out.****
Input array a : [[ 1.  2. nan]
 [ 4. nan  6.]
 [nan  8.  9.]]

 Output :
Element in Row 0 and Column 2 is nan
Element in Row 1 and Column 1 is nan
Element in Row 2 and Column 0 is nan


In [12]:
#9.	How to replace all missing values with 0 in a numpy array?
import numpy as np

a = np.array([[1,2, np.nan ],[4, np.nan ,6],[np.nan ,8, 9]])
print("****How to replace all missing values with 0 in a numpy array?****")
print("Input array a :", a)
n = a.shape
i = 0
j = 0
a[np.where(np.isnan(a))] = 0
print("Output array a :", a)


****How to replace all missing values with 0 in a numpy array?****
Input array a : [[ 1.  2. nan]
 [ 4. nan  6.]
 [nan  8.  9.]]
Output array a : [[1. 2. 0.]
 [4. 0. 6.]
 [0. 8. 9.]]


In [13]:
# 10.	How to find the count of each unique number in a NumPy array?
import numpy as np
a = np.array([[1,2,3,4,4],[4,5,3,1,2],[1,4,5,3,2]])
print("****10. How to find the count of each unique number in a NumPy array?****")
print("Input array a :", a)
b = [np.unique(a)]
print(b)
print("Count of unique number in array :", len(np.unique(a)))


****10. How to find the count of each unique number in a NumPy array?****
Input array a : [[1 2 3 4 4]
 [4 5 3 1 2]
 [1 4 5 3 2]]
[array([1, 2, 3, 4, 5])]
Count of unique number in array : 5


In [16]:
#11.	How to convert a numeric to a categorical (text) array?
import numpy as np
a = np.array([[35, 40, 65],[50, 65, 80],[95, 80, 50]],dtype=int)
print("****11. How to convert a numeric to a categorical (text) array?****")
print("<35 - Below Average \n 35 to 60 - Average \n >60 - Above Average")
print("Numeric array a :\n", a)
n = a.shape
x = len(a)
count = 0
i = 0
j = 0
for i in range(0,x):
    count += 1
b = np.empty((n[0],n[1]), dtype=object)
for i in range(0,n[0]):
    for j in range(0,n[1]): 
        if a[i][j] < 35:
            b[i][j] = "Below Average"
        elif a[i][j]>=35 and a[i][j]<=60:
            b[i][j] = "Average"
        else:
            b[i][j] = "Above Average"
print("\nCategorical Array :\n",b)


****11. How to convert a numeric to a categorical (text) array?****
<35 - Below Average 
 35 to 60 - Average 
 >60 - Above Average
Numeric array a :
 [[35 40 65]
 [50 65 80]
 [95 80 50]]

Categorical Array :
 [['Average' 'Average' 'Above Average']
 ['Average' 'Above Average' 'Above Average']
 ['Above Average' 'Above Average' 'Average']]


In [17]:
#12.	Write a program to print all numbers between 99 and 299 which are either divisible by 5 or 7. Exclude the elements which are divisible by both. 
import numpy as np

print("****12. Write a program to print all numbers between 99 and 299 which are either divisible by 5 or 7. Exclude the elements which are divisible by both. ****")
a = np.arange(99,300)
print("Input array a :\n", a)
n = len(a)
b = []
count = 0
i = 0
for i in range(0,n):
    if a[i]%5==0 or a[i]%7==0:
        if (a[i]%35!=0):
            b.append(a[i])
print("Numbers divisbile by 5 or 7, but not both : ", b)
print("Number of elements : ", len(b))


****12. Write a program to print all numbers between 99 and 299 which are either divisible by 5 or 7. Exclude the elements which are divisible by both. ****
Input array a :
 [ 99 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116
 117 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134
 135 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152
 153 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170
 171 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188
 189 190 191 192 193 194 195 196 197 198 199 200 201 202 203 204 205 206
 207 208 209 210 211 212 213 214 215 216 217 218 219 220 221 222 223 224
 225 226 227 228 229 230 231 232 233 234 235 236 237 238 239 240 241 242
 243 244 245 246 247 248 249 250 251 252 253 254 255 256 257 258 259 260
 261 262 263 264 265 266 267 268 269 270 271 272 273 274 275 276 277 278
 279 280 281 282 283 284 285 286 287 288 289 290 291 292 293 294 295 296
 297 298 299]
Numbers d

In [18]:
#13.	Write a program to reverse an array and print (Don’t use inbuilt reverse functions)
import numpy as np

print("****13. Write a program to reverse an array and print (Don’t use inbuilt reverse functions) ****")
a = np.array([[1,2,3,6],[4,5,6,7],[7,8,9,1]])
print("Input array a :\n", a)
n = a.shape
b = np.zeros((n[0],n[1]), dtype = int)
i = 0
j = 0
for i in range(0,n[0]):
    ind = 1
    for j in range(0,n[1]):
        b[i][j] = a[i][n[1]-ind]
        ind +=1
print("Reversed Array :\n ", b)



****13. Write a program to reverse an array and print (Don’t use inbuilt reverse functions) ****
Input array a :
 [[1 2 3 6]
 [4 5 6 7]
 [7 8 9 1]]
Reversed Array :
  [[6 3 2 1]
 [7 6 5 4]
 [1 9 8 7]]
